### ISSUE TITLE
Less space in details on desktop

### ISSUE THREAD

**Issue by madimadx** [CUHackers/cuhackit_2019#24]
Super on mobile! On desktop, need significantly less space between the rows.

**Comment by acarrab** [comment]
less space between rows? This is now what it currently looks like @madimadx 

![image](https://user-images.githubusercontent.com/8878541/35748525-58c4dc02-081c-11e8-9549-38a439881616.png)

**Comment by madimadx** [comment]
Not FAQs but the Details
<img width="985" alt="screen shot 2018-02-26 at 8 18 42 pm" src="https://user-images.githubusercontent.com/18021093/36705274-459389b6-1b32-11e8-8b11-c98e58312e6b.png">


The vertical distance between each row is too much. Could be decreased by 50% at least
