### ISSUE TITLE
Dynamically load differently sized images

### ISSUE THREAD

**Issue by acarrab** [CUHackers/cuhackit_2019#30]
We need to support different image sizes with something like this

```html
<img src="small.jpg" srcset="medium.jpg 1000w, large.jpg 2000w" alt="yah">
```

But we also need to downsize the images to make the proper choices. If anyone knows how to do that quickly please go ahead!

1. Create downsized versions of 
    - Grid backgrounds 
    - Sponsor Logos
1. Change the image tags to dynamically select the right sized images

Name the logos by their width such as `Blackbaud_500.png`  for Blackbaud image with 500px width.

**Comment by madimadx** [comment]
I can definitely do this later this afternoon.

**Comment by madimadx** [comment]
Jk. Just pushed image sizes to gh-pages. Will change image tags tonight.

**Comment by acarrab** [comment]
Thank you! Nice work!
