### ISSUE TITLE
Remove colored sponsors, replace with white sponsor logos

### ISSUE THREAD

**Issue by madimadx** [CUHackers/cuhackit_2019#33]
The logos on the site should be:
Siemens
Watt Center, Clemson Mobile
Blackbaud, Accenture
ITSAB, SciDAS

**Comment by acarrab** [comment]
# Clarifications
- We don't have a logo for Clemson Mobile. 
- You also want the font to be white for everything? 
  - I am a fan of at least having accents, but it is up to you still.
  - We also don't have white logos for all of the sponsors
- Clemson Mobile and Watt Center before companies?
  -  I think it is more impressive to have company sponsors although Watt did give up a lot for us and I know we appreciate it. 

These changes are up to you, but I am just letting you know what I am thinking.

Please let me know quickly so these changes can be made

**Comment by acarrab** [comment]
I also wanted to change to 3 columns format so it looks less cluttered.

Maybe I should reduce the spacing in this case too?

## fully expanded

![image](https://user-images.githubusercontent.com/8878541/36747648-666d4794-1baa-11e8-86b7-7200b11275ab.png)

## Then on shrinking...

![image](https://user-images.githubusercontent.com/8878541/36747685-7ffd84a8-1baa-11e8-8f73-1c33e58b247c.png)

## Smallest

![image](https://user-images.githubusercontent.com/8878541/36747714-9743e6ac-1baa-11e8-9b43-c3367bfef943.png)

**Comment by madimadx** [comment]
Good call on having more sponsor columns.

Though I understand the concern that companies look more impressive as sponsors than buildings, the sponsors will be ordered in this order based on contributions: Siemens, Fusion 360 (fresh sponsor), Clemson Mobile, Blackbaud, Accenture, SciDAS, Watt Center, ITSAB.

On color, I would like to try out keeping Siemen's colored logo because it contrasts well with the black, but solid white for all the other ones because (1) it stands out the best on the dark background while the colored logos don't (2) design-wise, it looks cleaner
- I've uploaded white sponsor logos to CUhackit/Design/Sponsor Logos/White logos
- diff. sizes for rasters, .svg for companies that sent a vector logo

You're right -- the vertical space needs to be smaller in every format, but especially for the smallest (one-column).

**Comment by madimadx** [comment]
@acarrab uploaded new Watt logo to drive

**Comment by madimadx** [comment]
@acarrab uploaded new Fusion360 logo to drive. Should be the LAST thing for this issue.
