### ISSUE TITLE
In Details section, left align text

### ISSUE THREAD

**Issue by madimadx** [CUHackers/cuhackit_2019#34]
Currently is all center aligned. Please left align.

**Comment by acarrab** [comment]
I don't think that looks good. I don't like how it is now either, but it looks worse left aligned. Suggestions?

![image](https://user-images.githubusercontent.com/8878541/36746424-24fa435a-1ba7-11e8-8d0e-2663c9c8b9a5.png)

**Comment by madimadx** [comment]
Try left aligning the headers as well

**Comment by acarrab** [comment]
That looks better. Good? 

![image](https://user-images.githubusercontent.com/8878541/36747861-002f48a0-1bab-11e8-85a3-1e9899923148.png)

**Comment by madimadx** [comment]
Definitely like it. 

I think this space as well as the bottom space is too much now:
<img width="1119" alt="screen shot 2018-02-27 at 11 02 51 pm" src="https://user-images.githubusercontent.com/18021093/36769459-6a22cc7a-1c12-11e8-91fd-1f11064faf6d.png">

<img width="1064" alt="screen shot 2018-02-27 at 11 02 56 pm" src="https://user-images.githubusercontent.com/18021093/36769473-7aeb207a-1c12-11e8-9733-1f83d6472fae.png">

Maybe make both closer to the size of this gap

<img width="1059" alt="screen shot 2018-02-27 at 11 04 02 pm" src="https://user-images.githubusercontent.com/18021093/36769522-b13c069e-1c12-11e8-8744-1990fbbd684d.png">
