### ISSUE TITLE
In details, replace current header with this graphic 

### ISSUE THREAD

**Issue by madimadx** [CUHackers/cuhackit_2019#35]
![headerblack](https://user-images.githubusercontent.com/18021093/36705618-1f49860a-1b34-11e8-9f2d-52ee52dc5b29.png)

In drive: CUhackit/Design/headerBlack.png

**Comment by acarrab** [comment]
I did this, but changed the text color to white for the </DESIGN BUILD CODE> text

**Comment by madimadx** [comment]
I'll upload a new one to replace with. My bad.

**Comment by madimadx** [comment]
Replace with In drive: CUhackit/Design/headerWhite.png
